import re

path = '/opt/autosparefinder/backend/supplier_pdf_import.py'
text = open(path, encoding='utf-8').read()

fn_pattern = re.compile(
    r'^def _parse_text_fallback\(pdf_path, manufacturer\):\n.*?^# --- DB operations ---',
    re.MULTILINE | re.DOTALL
)
m = fn_pattern.search(text)
if not m:
    print("ERROR: function not found"); raise SystemExit(1)

# Build the new function as a plain string (no heredoc, no escaping issues)
lines = [
    'def _parse_text_fallback(pdf_path, manufacturer):',
    '    """',
    '    Fast text extraction for large PDFs (>150 pages).',
    '    Strategy:',
    '      1. Try PyMuPDF (fitz) text extraction + line-regex (very fast ~2s).',
    '      2. If yield < threshold (e.g. column-layout PDFs like Mitsubishi where',
    '         fitz gives few regex-matchable lines), fall back to pdfminer',
    '         extract_pages() + _parse_column_page() which handles RTL column PDFs.',
    '    This avoids the 339s pdfminer-for-all-pages penalty on large plain-text PDFs',
    '    while still correctly handling column-layout PDFs.',
    '    """',
    '    import fitz  # PyMuPDF - fast extraction',
    '',
    '    # ── Step 1: fast fitz extraction ────────────────────────────────────',
    '    fitz_rows = []',
    '    n_pages = 0',
    '    try:',
    '        doc = fitz.open(pdf_path)',
    '        n_pages = len(doc)',
    '        log.info("Text fallback: %d pages via PyMuPDF", n_pages)',
    '        fitz_lines = []',
    '        for page in doc:',
    '            fitz_lines.extend(page.get_text("text").splitlines())',
    '        doc.close()',
    '        for line in fitz_lines:',
    '            line_up = line.upper().strip()',
    '            if not line_up:',
    '                continue',
    '            oem_matches = list(_OEM_PAT.finditer(line_up))',
    '            if not oem_matches:',
    '                continue',
    '            oem_raw = oem_matches[-1].group(1)',
    '            if not (re.search(r\'[A-Z]\', oem_raw) and re.search(r\'[0-9]\', oem_raw)):',
    '                continue',
    '            nk = normalize_key(oem_raw)',
    '            if not nk or len(nk) < 4:',
    '                continue',
    '            price = None',
    '            for pm in _PRICE_PAT.finditer(line):',
    '                try:',
    '                    price = parse_price(pm.group(1))',
    '                    if price and price > 0:',
    '                        break',
    '                except Exception:',
    '                    pass',
    '            avail = True',
    '            if "\\u05dc\\u05d0 \\u05d6\\u05de\\u05d9\\u05df" in line or "unavail" in line_up:',
    '                avail = False',
    '            fitz_rows.append(PdfRow(',
    '                oem_number=oem_raw,',
    '                oem_norm=nk,',
    '                name=f"{manufacturer.upper()} {nk}",',
    '                price=price,',
    '                available=avail,',
    '            ))',
    '    except Exception as e:',
    '        log.warning("PyMuPDF extraction failed: %s", e)',
    '',
    '    # Threshold: fitz must yield at least 1 row per 10 pages to be considered good.',
    '    # Column-layout PDFs (Mitsubishi) yield ~0 rows via line-regex; plain-text yields 1000s.',
    '    min_expected = max(20, n_pages // 10)',
    '    if len(fitz_rows) >= min_expected:',
    '        log.info("PyMuPDF yield %d rows (threshold %d) — using fitz result", len(fitz_rows), min_expected)',
    '        rows = fitz_rows',
    '    else:',
    '        # ── Step 2: pdfminer column extraction (column-layout PDFs) ────',
    '        log.info("PyMuPDF yield %d rows < threshold %d — falling back to pdfminer column extraction",',
    '                 len(fitz_rows), min_expected)',
    '        from pdfminer.high_level import extract_pages as _extract_pages',
    '        from pdfminer.layout import LTTextContainer as _LTText',
    '        rows = []',
    '        try:',
    '            for page_layout in _extract_pages(pdf_path):',
    '                try:',
    '                    elems = [',
    '                        (el.x0, el.get_text())',
    '                        for el in page_layout',
    '                        if isinstance(el, _LTText) and el.get_text().strip()',
    '                    ]',
    '                    rows.extend(_parse_column_page(elems, manufacturer))',
    '                except Exception:',
    '                    continue',
    '        except Exception as e:',
    '            log.warning("pdfminer column extraction failed: %s", e)',
    '',
    '    seen, unique = set(), []',
    '    for r in rows:',
    '        if r.oem_norm not in seen:',
    '            seen.add(r.oem_norm)',
    '            unique.append(r)',
    '    log.info("Text fallback: %d unique keys", len(unique))',
    '    return unique',
    '',
    '',
    '# --- DB operations ---',
]

new_fn = '\n'.join(lines)
fixed = text[:m.start()] + new_fn + text[m.end():]
open(path, 'w', encoding='utf-8').write(fixed)
print("Replaced OK")
