"""
social/post_guard.py — semantic guard for NOA's generated posts.

WHY THIS EXISTS (2026-07-29). NOA published a post describing windscreen WIPERS
(`מגבי שמשה`) as giving "הגנה מפני קרני השמש, חיסכון בדלק והפחתת טמפרטורת הפנים"
— sun protection, fuel savings, cooler cabin. Those are the benefits of a
SUNSHADE. The Hebrew was fluent and grammatical; the MEANING was wrong.

That distinction matters for choosing the fix:
  • It is NOT a language-skill problem, so a stronger Hebrew generator would only
    produce more fluent nonsense.
  • It is a GROUNDING problem — the generator free-associates from a part name it
    does not understand, then writes confident marketing copy around the guess.

So the generator proposes and the LOCAL multilingual embedding model
(paraphrase-multilingual-MiniLM-L12-v2, already installed, he/ar/en) JUDGES: does
this copy actually describe THIS part? Same shape as the Phase-1 controlled write
path used for categorisation — the LLM proposes, the local model gates.

THRESHOLD IS MEASURED, NOT GUESSED (12 real parts, one per category, copy
generated by the live LLM):

    MATCHED  (copy about its own part)   mean 0.653   min 0.487
    MISMATCH (copy about another part)   mean 0.296   max 0.390

    threshold 0.30 -> accepts 58.3% of MISMATCH
    threshold 0.35 -> accepts  8.3% of MISMATCH
    threshold 0.40 -> accepts  0.0% of MISMATCH, rejects 0.0% of MATCHED  <=

0.40 sits in the gap (0.390 -> 0.487) with margin both ways, and independently
matches the real production failure: correct wiper copy scored 0.515 (passes),
the published wrong copy 0.269 (rejected).

A FIRST attempt at this measurement compared each part to its own first six words
and reported MATCHED=0.920 — near-duplicate text, not marketing prose. That would
have set the threshold near 0.50 and rejected legitimate posts. Only generating
REAL copy exposed it. If you re-tune this number, re-tune it on real generated
copy.

CAVEATS BUILT IN
  • n=12 is enough to show separation, not enough to be certain at the edges —
    so every score is LOGGED for re-tuning on real traffic.
  • Scoring MUST fail OPEN. Two of the twelve generations hit provider 429s; an
    embedding error or a missing model must never block publishing. A post that
    cannot be scored is allowed and flagged.

Data Modified: none (pure evaluation)
Last Updated:  2026-07-29
"""
from __future__ import annotations

import logging
import os
from typing import Optional, Tuple

logger = logging.getLogger("post_guard")

# RECALIBRATED 2026-07-20 on real NOA marketing captions (the original 0.40 came from
# n=12 short synthetic pairs and REJECTED legitimate posts). Measured on real captions:
#   • correct part  → 0.227, 0.252, 0.372, 0.483  (min 0.227)
#   • gross grounding failure (the class this guard exists to catch, e.g. wiper-blade
#     copy sold as a SUNSHADE) → 0.076, 0.099
# A long emoji/price/CTA caption vs a short part label is inherently low-cosine, so there
# is NO clean cut for SUBTLE same-domain mixups (battery-vs-wiper scored 0.384) — and the
# guard is explicitly fail-OPEN (a rare wrong post beats halting all posting). 0.15 sits
# below every legitimate post and above the gross-failure band: it catches the
# sunshade-class error without silently killing real posts. Env-tunable.
MIN_SIM = float(os.getenv("NOA_GUARD_MIN_SIM", "0.15"))
ENABLED = os.getenv("NOA_GUARD_ENABLED", "1").strip().lower() in ("1", "true", "yes")


def _cosine(a, b) -> float:
    import numpy as np
    a, b = np.asarray(a, dtype="float32"), np.asarray(b, dtype="float32")
    na, nb = float((a * a).sum()) ** 0.5, float((b * b).sum()) ** 0.5
    if na <= 0 or nb <= 0:
        return 0.0
    return float(a @ b / (na * nb))


def score(post: str, part_text: str) -> Optional[float]:
    """Cosine similarity between the post and the part it claims to be about.

    Returns None when scoring is unavailable — callers MUST treat None as
    "cannot judge" and allow the post through.
    """
    post = (post or "").strip()
    part_text = (part_text or "").strip()
    if not post or not part_text:
        return None
    try:
        import category_embed as ce
        if not ce.available():
            return None
        vecs = ce.embed([part_text, post])
        return _cosine(vecs[0], vecs[1])
    except Exception as exc:                      # provider/model/runtime failure
        logger.warning("post_guard: scoring unavailable (%s) — failing OPEN",
                       type(exc).__name__)
        return None


def check(post: str, part_text: str, *, context: str = "") -> Tuple[bool, Optional[float]]:
    """(ok, score). ok=False ONLY when a score was obtained and it is below MIN_SIM.

    Fails OPEN by design: no score => ok=True. Blocking NOA because an embedding
    call failed would trade a rare wrong post for a silent halt of all posting.
    """
    if not ENABLED:
        return True, None
    s = score(post, part_text)
    if s is None:
        logger.info("post_guard: UNSCORED (allowed) %s", context)
        return True, None
    ok = s >= MIN_SIM
    # Log EVERY score, pass or fail — the threshold came from n=12 and needs real
    # traffic to be tuned properly.
    logger.info("post_guard: sim=%.3f threshold=%.2f verdict=%s %s",
                s, MIN_SIM, "OK" if ok else "REJECT", context)
    return ok, s


def part_text_for(name: str = "", name_he: str = "", category: str = "",
                  description: str = "") -> str:
    """Build the part's identity string the guard scores against.

    Uses the Hebrew DISPLAY name of the category (never the stored slug) so the
    text reads as natural language to a multilingual sentence model.
    """
    cat_he = ""
    try:
        from category_map import DISPLAY
        cat_he = (DISPLAY.get(category) or {}).get("he") or ""
    except Exception:
        cat_he = category or ""
    bits = [(name_he or name or "").strip(), cat_he, (description or "")[:160].strip()]
    return " ".join(b for b in bits if b).strip()


__all__ = ["check", "score", "part_text_for", "MIN_SIM", "ENABLED"]
