"""Fix parts_catalog.embedding dimension: 768 → 384

The embedding model was changed from nomic-embed-text (768-dim) to
sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 (384-dim).
Inserting a 384-dim vector into a vector(768) column raises:
  ERROR: expected 768 dimensions, not 384

Strategy: drop IVFFlat index, drop column, re-add at 384 dims, rebuild index.
The column is nullable so existing rows are unaffected (embeddings are
regenerated by running generate_embeddings.py after the migration).

Revision ID: 0027
Revises: 0026_truck_brands
Create Date: 2026-03-28
"""
from alembic import op

revision = "0027"
down_revision = "0026_truck_brands"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Drop old index (references the 768-dim column)
    op.execute("DROP INDEX IF EXISTS idx_parts_catalog_embedding")

    # 2. Drop and re-add column at 384 dims — null-safe, no data loss
    #    (pgvector cannot ALTER TYPE vector(768) to vector(384) via CAST)
    op.execute("ALTER TABLE parts_catalog DROP COLUMN IF EXISTS embedding")
    op.execute(
        "ALTER TABLE parts_catalog "
        "ADD COLUMN embedding vector(384)"
    )

    # 3. Rebuild IVFFlat index for cosine similarity at 384 dims
    op.execute("""
        CREATE INDEX idx_parts_catalog_embedding
        ON parts_catalog
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 100)
        WHERE embedding IS NOT NULL
    """)


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS idx_parts_catalog_embedding")
    op.execute("ALTER TABLE parts_catalog DROP COLUMN IF EXISTS embedding")
    op.execute(
        "ALTER TABLE parts_catalog "
        "ADD COLUMN embedding vector(768)"
    )
    op.execute("""
        CREATE INDEX idx_parts_catalog_embedding
        ON parts_catalog
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 100)
        WHERE embedding IS NOT NULL
    """)
