"""Fix parts_catalog.embedding dimension for production embeddings (1536)

Set parts_catalog.embedding to 1536-dimensional vectors for current runtime compatibility.
Ensure parts_catalog.embedding remains vector(1536).

Strategy: drop old index, drop column, re-add at 1536 dims, rebuild HNSW index.
The column is nullable so existing rows are unaffected (embeddings are
regenerated by running generate_embeddings.py after the migration).

Revision ID: 0027
Revises: 0026_truck_brands
Create Date: 2026-03-28
"""
from alembic import op

revision = "0027"
down_revision = "0026_truck_brands"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Drop old index (references embedding column)
    op.execute("DROP INDEX IF EXISTS idx_parts_catalog_embedding")

    # 2. Drop and re-add column at 1536 dims — null-safe, no data loss
    #    (pgvector cannot ALTER TYPE vector dimensions via CAST)
    op.execute("ALTER TABLE parts_catalog DROP COLUMN IF EXISTS embedding")
    op.execute(
        "ALTER TABLE parts_catalog "
        "ADD COLUMN embedding vector(1536)"
    )

    # 3. Rebuild HNSW index for cosine similarity
    op.execute("""
        CREATE INDEX idx_parts_catalog_embedding
        ON parts_catalog
        USING hnsw (embedding vector_cosine_ops)
        WHERE embedding IS NOT NULL
    """)


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS idx_parts_catalog_embedding")
    op.execute("ALTER TABLE parts_catalog DROP COLUMN IF EXISTS embedding")
    op.execute(
        "ALTER TABLE parts_catalog "
        "ADD COLUMN embedding vector(1536)"
    )
    op.execute("""
        CREATE INDEX idx_parts_catalog_embedding
        ON parts_catalog
        USING hnsw (embedding vector_cosine_ops)
        WHERE embedding IS NOT NULL
    """)
