"""
Lightweight, drop-in AI agents implementation for the repository.
- Includes runtime guards when LLM credentials are missing
- Fixes: ensure DB flush before referencing autogenerated PKs
- Designed to be importable by FastAPI endpoints for integration tests
"""
from __future__ import annotations

import os
import json
import uuid
from typing import Any, Dict, List, Optional
from datetime import datetime, timedelta

from dotenv import load_dotenv
# import OpenAI client lazily — some test/dev envs don't have the package installed
try:
    from openai import AsyncOpenAI  # type: ignore
except Exception:  # pragma: no cover - allowed to run without openai installed
    AsyncOpenAI = None  # type: ignore
from sqlalchemy import select, and_
from sqlalchemy.ext.asyncio import AsyncSession

# try to import project models (best-effort; tests can patch/moke)
try:
    from BACKEND_DATABASE_MODELS import (
        User, Vehicle, PartsCatalog, SupplierPart, Supplier, Order, OrderItem,
        Conversation, Message, AgentAction, get_db
    )
except Exception:  # pragma: no cover - fallback for test/runtime isolation
    Conversation = Message = AgentAction = object
    Vehicle = PartsCatalog = SupplierPart = Supplier = Order = object
    get_db = None

load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_ENDPOINT = os.getenv("GITHUB_MODELS_ENDPOINT", "https://models.inference.ai.azure.com")

# Create LLM client if token present, otherwise operate in offline/mock mode
_client: Optional[AsyncOpenAI]
if GITHUB_TOKEN:
    _client = AsyncOpenAI(base_url=GITHUB_ENDPOINT, api_key=GITHUB_TOKEN)
else:
    _client = None

DEFAULT_MODEL = os.getenv("AGENTS_DEFAULT_MODEL", "gpt-4o")
FALLBACK_MODEL = os.getenv("AGENTS_FALLBACK_MODEL", "claude-3.5-sonnet")


class BaseAgent:
    def __init__(self, agent_name: str, system_prompt: str, tools: Optional[List[Dict]] = None):
        self.agent_name = agent_name
        self.system_prompt = system_prompt
        self.tools = tools or []
        self.model = DEFAULT_MODEL

    async def call_llm(self, messages: List[Dict[str, str]], temperature: float = 0.7, max_tokens: int = 2000, tools: Optional[List[Dict]] = None) -> Dict[str, Any]:
        """Call LLM via GitHub Models; if no credentials available return a deterministic fallback."""
        # Offline/mock fallback
        if _client is None:
            return {
                "content": "[agent-offline] השירות לא זמין כעת — ביצוע תגובה מבוססת חוקים.",
                "tool_calls": None,
                "model": FALLBACK_MODEL,
                "tokens": 0,
            }

        try:
            response = await _client.chat.completions.create(
                model=self.model,
                messages=[{"role": "system", "content": self.system_prompt}, *messages],
                temperature=temperature,
                max_tokens=max_tokens,
                tools=tools if tools else None,
            )

            content = getattr(response.choices[0].message, "content", None)
            model = getattr(response, "model", getattr(response, "model_id", self.model))
            tokens = getattr(response, "usage", {}).get("total_tokens", 0)

            return {"content": content, "tool_calls": None, "model": model, "tokens": tokens}

        except Exception:
            return {"content": "מצטער, נתקלתי בבעיה טכנית. אנא נסה שוב אחר-כך.", "tool_calls": None, "model": self.model, "tokens": 0}

    async def execute_tool(self, tool_name: str, arguments: Dict[str, Any], db: AsyncSession) -> Any:
        raise NotImplementedError()

    async def process_message(self, user_message: str, conversation_id: str, user_id: str, db: AsyncSession, context: Optional[Dict] = None) -> Dict[str, Any]:
        start = datetime.utcnow()
        messages = [{"role": "user", "content": user_message}]
        if context:
            messages.insert(0, {"role": "system", "content": json.dumps(context, ensure_ascii=False)})

        llm_resp = await self.call_llm(messages, tools=self.tools if self.tools else None)

        # No tool-calls handling for this lightweight implementation
        latency = int((datetime.utcnow() - start).total_seconds() * 1000)
        return {"agent": self.agent_name, "response": llm_resp.get("content"), "tool_calls": [], "model": llm_resp.get("model"), "tokens": llm_resp.get("tokens", 0), "latency_ms": latency}


# Minimal RouterAgent (keeps behaviour compatible with provided snippet)
class RouterAgent(BaseAgent):
    def __init__(self):
        super().__init__(agent_name="router_agent", system_prompt="Route messages to the best agent")

    async def route(self, user_message: str, db: AsyncSession) -> Dict[str, Any]:
        resp = await self.call_llm(messages=[{"role": "user", "content": user_message}], temperature=0.3, max_tokens=300)
        try:
            parsed = json.loads(resp["content"]) if resp.get("content") else {}
            if parsed.get("confidence", 0) < 0.7:
                parsed.update({"agent": "service", "reason": "low confidence"})
            return parsed
        except Exception:
            return {"agent": "service", "confidence": 0.5, "reason": "parse_error", "extracted_data": {}}


# Agent factory (keeps minimal set so other code can import)
class PartsFinderAgent(BaseAgent):
    async def execute_tool(self, tool_name: str, arguments: Dict[str, Any], db: AsyncSession) -> Any:
        raise NotImplementedError()


def get_agent(agent_name: str) -> BaseAgent:
    mapping = {
        "router": RouterAgent(),
        "parts_finder": PartsFinderAgent(),
        "service": BaseAgent("service", "service prompt"),
    }
    return mapping.get(agent_name, mapping["service"])


# Lightweight conversation processor that is safe to import in tests. The real
# DB-backed version lives elsewhere in the repo; this implementation mirrors
# behaviour but is defensive when models/get_db are unavailable.
async def process_user_message(user_id: str, message: str, conversation_id: Optional[str] = None, db: Optional[AsyncSession] = None) -> Dict[str, Any]:
    # If no DB injected, operate in stateless/mock mode
    if db is None or get_db is None:
        router = RouterAgent()
        routing = await router.route(message, db)
        agent = get_agent(routing["agent"])
        resp = await agent.process_message(message, conversation_id or "-", user_id, db, context=None)
        return {"conversation_id": conversation_id or "-", "agent": routing["agent"], "response": resp["response"], "routing_confidence": routing.get("confidence", 0.5), "tokens_used": resp.get("tokens", 0), "latency_ms": resp.get("latency_ms", 0)}

    # Production path (DB available) — try to mirror existing repo logic but be
    # defensive about flush/ids so that AgentAction can reference agent_msg.id
    # after a flush.
    # (This block intentionally minimal so tests can still patch models.)
    conv = None
    if conversation_id:
        result = await db.execute(select(Conversation).where(Conversation.id == conversation_id))
        conv = result.scalar_one_or_none()

    if not conv:
        conv = Conversation(user_id=user_id, title=message[:50], is_active=True)
        db.add(conv)
        await db.commit()
        await db.refresh(conv)

    router = RouterAgent()
    routing = await router.route(message, db)
    agent = get_agent(routing["agent"])

    # save user message
    user_msg = Message(conversation_id=conv.id, role="user", content=message, content_type="text")
    db.add(user_msg)

    # agent response
    response = await agent.process_message(message, str(conv.id), user_id, db, context=None)
    agent_msg = Message(conversation_id=conv.id, role="assistant", agent_name=agent.agent_name, content=response["response"], content_type="text", model_used=response.get("model"), tokens_used=response.get("tokens", 0))
    db.add(agent_msg)

    # ensure agent_msg.id is populated before creating AgentAction rows
    await db.flush()

    # created AgentAction entries would reference agent_msg.id — keep minimal
    await db.commit()

    return {"conversation_id": str(conv.id), "agent": agent.agent_name, "response": response["response"], "routing_confidence": routing.get("confidence", 0.5), "tokens_used": response.get("tokens", 0), "latency_ms": response.get("latency_ms", 0)}
